-- phpMyAdmin SQL Dump
-- version 4.8.5
-- https://www.phpmyadmin.net/
--
-- Host: 127.0.0.1:3306
-- Generation Time: Dec 19, 2019 at 01:33 PM
-- Server version: 5.7.26
-- PHP Version: 7.2.18

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET AUTOCOMMIT = 0;
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `bookstore`
--

-- --------------------------------------------------------

--
-- Table structure for table `categories`
--

DROP TABLE IF EXISTS `categories`;
CREATE TABLE IF NOT EXISTS `categories` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `name` varchar(100) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=26 DEFAULT CHARSET=latin1;

--
-- Dumping data for table `categories`
--

INSERT INTO `categories` (`id`, `name`) VALUES
(1, 'Arts & Music'),
(2, 'Biographies'),
(3, 'Business'),
(4, 'Kids'),
(5, 'Comics'),
(6, 'Computers & Tech'),
(7, 'Cooking'),
(8, 'Hobbies & Crafts'),
(9, 'Edu & Reference'),
(10, 'Health & Fitness'),
(11, 'History'),
(12, 'Home & Garden'),
(13, 'Horror'),
(14, 'Entertainment'),
(15, 'Literature & Fiction'),
(16, 'Medical'),
(17, 'Mysteries'),
(18, 'Parenting'),
(19, 'Social Sciences'),
(20, 'Religion'),
(21, 'Science & Math'),
(22, 'Self-Help'),
(23, 'Sports'),
(24, 'Teen'),
(25, 'Travel');

-- --------------------------------------------------------

--
-- Table structure for table `orders`
--

DROP TABLE IF EXISTS `orders`;
CREATE TABLE IF NOT EXISTS `orders` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `product_name` text NOT NULL,
  `quantity` int(11) NOT NULL,
  `total_price` int(11) NOT NULL,
  `customer_name` text NOT NULL,
  `email` text NOT NULL,
  `address` text NOT NULL,
  `order_date` date NOT NULL,
  `payment_confirm` tinyint(1) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=10 DEFAULT CHARSET=latin1;

--
-- Dumping data for table `orders`
--

INSERT INTO `orders` (`id`, `product_name`, `quantity`, `total_price`, `customer_name`, `email`, `address`, `order_date`, `payment_confirm`) VALUES
(1, 'A Small Place', 1, 5, 'abc', 'abc', 'abc', '2019-12-19', 1),
(2, 'The curve of time', 1, 6, 'abc', 'abc', 'abc', '2019-12-19', 1),
(3, 'When Heaven and Earth Changed Places', 2, 10, 'abc', 'abc', 'abc', '2019-12-19', 1),
(6, 'Out of Africa: and Shadows on the Grass', 1, 5, 'abc', 'abc', 'abc', '2019-12-19', 1);

-- --------------------------------------------------------

--
-- Table structure for table `products`
--

DROP TABLE IF EXISTS `products`;
CREATE TABLE IF NOT EXISTS `products` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `category_id` int(11) NOT NULL,
  `title` varchar(225) NOT NULL,
  `description` text NOT NULL,
  `image` varchar(100) NOT NULL,
  `price` decimal(10,2) NOT NULL,
  PRIMARY KEY (`id`),
  KEY `category_id` (`category_id`)
) ENGINE=InnoDB AUTO_INCREMENT=102 DEFAULT CHARSET=latin1;

--
-- Dumping data for table `products`
--

INSERT INTO `products` (`id`, `category_id`, `title`, `description`, `image`, `price`) VALUES
(10, 1, 'Then Sings My Soul: 150 of the World\'s Greatest Hymn Stories', 'Rob Morgan\'s inimitable style will help people reacquaint themselves with the hymns of the faithful. His goal is to keep these traditional hymns vital and meaningful to all generations.Don\'t look for a dry recounting of boring stories. These devotional-style stories show the emotion and drama behind the hymns of faith that have changed many lives throughout history -- the people whose faith led them to write these wonderful hymns and the people whose faith was affected by reading, hearing, and singing the songs. Designed to be personally reflective, these stories speak to your soul and add depth and meaning as you worship God through song.FEATURES:Includes words and music to each hymnSpecial softcover, french flap cover designIvory paper with brown inkJagged-edge paper, giving it a classic feelComplete with hymn indexUse for devotionals, teaching illustrations, introductory remarks for song leaders and music ministers', 'then-sings-my-soul-150-of-the-worlds-greatest-hymn-stories_robert-j-morgan.jpg', '6.09'),
(11, 1, 'Watercolor School', 'Provides visual explanations and simple exercises to build painting skills, and offers eight projects highlighting different subjects from the planning stage to the completed painting', 'watercolor-school-learn-as-you-go_hazel-harrison.jpg', '4.69'),
(12, 1, 'Screenplay : The Foundations of Screenwriting', 'Hollywood\'s script guru teaches you how to write a screenplay in \"the \'bible\' of screenwriting\" ( The New York Times )--now celebrating forty years of screenwriting success Syd Field\'s books on the essential structure of emotionally satisfying screenplays have ignited lucrative careers in film and television since 1979. In this revised edition of his premiere guide, the underpinnings of successful onscreen narratives are revealed in clear and encouraging language that will remain wise and practical as long as audiences watch stories unfold visually--from hand-held devices to IMAX to virtual reality . . . and whatever comes next. As the first person to articulate common structural elements unique to successful movies, celebrated producer, lecturer, teacher and bestselling author Syd Field has gifted us a classic text. From concept to character, from opening scene to finished script, here are fundamental guidelines to help all screenwriters--novices and Oscar-winners--hone their craft and sell their work. In Screenplay , Syd Field can help you discover: - Why the first ten pages of every script are crucial to keeping professional readers\' interest - How to visually \"grab\" these influential readers from page one, word one - Why structure and character are the basic components of all narrative screenplays - How to adapt a novel, a play, or an article into a saleable script - Tips on protecting your work--three ways to establish legal ownership of screenplays - Vital insights on writing authentic dialogue, crafting memorable characters, building strong yet flexible storylines (form, not formula), overcoming writer\'s block, and much more Syd Field is revered as the original master of screenplay story structure, and this guide continues to be the industry\'s gold standard for learning the foundations of screenwriting.', 'the-screenwriters-workbook-a-workshop-approach_syd-field.jpg', '9.99'),
(13, 1, 'The Digital Photography', 'This is it--the #1 best-selling digital photography book ever It\'s the award winning, worldwide smash hit, written by Scott Kelby, that\'s been translated into dozens of different languages, because it\'s the one book that really shows you how to take professional-quality shots using the same tricks today\'s top digital pros use (and surprisingly, it\'s easier than you\'d think). This updated, second edition of the bestselling digital photography book of all time includes many new images; up-to-date information on gear, pricing, and links; and a new chapter from the author on the \"Ten Things I Wish Someone Had Told Me When I Was First Starting Out in Photography.\" Here\'s how Scott describes this book\'s brilliant premise: \"If you and I were out on a shoot, and you asked me, \'Hey, how do I get this flower to be in focus, with the background out of focus?, \' I wouldn\'t stand there and give you a photography lecture. In real life, I\'d just say, \'Put on your zoom lens, set your f-stop to f/2.8, focus on the flower, and fire away.\' That\'s what this book is all about: you and I out shooting where I answer questions, give you advice, and share the secrets I\'ve learned just like I would with a friend--without all the technical explanations and techie photo speak.\" This isn\'t a book of theory--full of confusing jargon and detailed concepts. This is a book on which button to push, which setting to use, and when to use it. With over 200 of the most closely guarded photographic \"tricks of the trade,\" this book gets you shooting dramatically better-looking, sharper, more colorful, more professional-looking photos every time. Each page covers a single concept that makes your photography better. Every time you turn the page, you\'ll learn another pro setting, tool, or trick to transform your work from snapshots into gallery prints. If you\'re tired of taking shots that look \"okay,\" and if you\'re tired of looking in photography magazines and thinking, \"Why don\'t my shots look like that?\" then this is the book for you.', 'the-digital-photography-book_scott-kelby.jpg', '5.99'),
(14, 1, 'Sculpture : Principles and Practice', '\"Instruction and appreciation become one in this book.\" School Arts Sculpture: Principles and Practice is one of the most authoritative and comprehensive books on the creation of sculpture. Unlike other instructional guides by people who have never had their fingers wet with clay, this book is the accumulation of many years of practical knowledge and experience by a noted American sculptor and art instructor. Mr. Slobodkin starts with the very basics of the art and leaves no area uncovered. He advises the novice what type of material is best to work with, and in a step-by-step process shows how to begin with elementary forms and proceed to the more complex, used for creating human figures, portrait heads, bas reliefs, and other forms of sculpture. Helpful instruction and diagrams of the proper procedure for constructing armatures and the proper methods for the use of tools are passed on to the reader along the way. When the use of clay and plasteline are well in hand, Mr. Slobodkin moves to the handling of more difficult materials. Plaster casting, wood carving, stone carving, terra cotta, metal sculpture, and architectural sculpture are all covered with hundreds of drawings and progressive photographs to add clarity. A most welcome aspect of this book is the author\'s witty and readable style. Technical passages never become oppressive, and words of encouragement and inspiration are offered frequently. One is well aware that the author was once a novice and facing the same difficulties himself. For the beginner this book is invaluable, but even those who have been sculpting for years will find the latter chapters full of helpful hints and useful information.', 'sculpture-principles-and-practice_louis-slobodkin.jpg', '4.25'),
(15, 2, 'Narrative of the Life of Frederick Douglas : An American Slave', 'Former slave, impassioned abolitionist, brilliant writer, newspaper editor and eloquent orator whose speeches fired the abolitionist cause, Frederick Douglass (1818-1895) led an astounding life. Physical abuse, deprivation and tragedy plagued his early years, yet through sheer force of character he was able to overcome these obstacles to become a leading spokesman for his people. In this, the first and most frequently read of his three autobiographies, Douglass provides graphic descriptions of his childhood and horrifying experiences as a slave as well as a harrowing record of his dramatic escape to the North and eventual freedom. Published in 1845 to quell doubts about his origins -- since few slaves of that period could write -- the Narrative is admired today for its extraordinary passion, sensitive and vivid descriptions and storytelling power. It belongs in the library of anyone interested in African-American history and the life of one of the country\'s most courageous and influential champions of civil rights.', 'narrative-of-the-life-of-frederick-douglass_frederick-douglass.jpg', '4.79'),
(16, 2, 'The 48 Laws of Power', 'Amoral, cunning, ruthless, and instructive, this multi-million-copy New York Times bestseller is the definitive manual for anyone interested in gaining, observing, or defending against ultimate control - from the author of The Laws of Human Nature. In the book that People magazine proclaimed \"beguiling\" and \"fascinating,\" Robert Greene and Joost Elffers have distilled three thousand years of the history of power into 48 essential laws by drawing from the philosophies of Machiavelli, Sun Tzu, and Carl Von Clausewitz and also from the lives of figures ranging from Henry Kissinger to P.T. Barnum. Some laws teach the need for prudence (\"Law 1: Never Outshine the Master\"), others teach the value of confidence (\"Law 28: Enter Action with Boldness\"), and many recommend absolute self-preservation (\"Law 15: Crush Your Enemy Totally\"). Every law, though, has one thing in common: an interest in total domination. In a bold and arresting two-color package, The 48 Laws of Power is ideal whether your aim is conquest, self-defense, or simply to understand the rules of the game.', 'the-48-laws-of-power_robert-greene.jpg', '16.29'),
(17, 2, 'Team of Rivals: The Political Genius of Abraham Lincoln', 'No Synopsis Available.', 'team-of-rivals-the-political-genius-of-abraham-lincoln-by-doris-kearns-goodwin.jpg', '4.69'),
(18, 3, 'The Wealthy Barber', 'No Synopsis Available.', 'the-wealthy-barber-the-common-sense-guide-to-successful-financial-planning_david-h-chilton.jpg', '4.79'),
(19, 3, 'Think and Grow Rich', 'Please note that this item is a roughcut (deckle edge) editionThink and Grow Rich has been called the \"Granddaddy of All Motivational Literature.\" It was the first book to boldly ask, \"What makes a winner?\" The man who asked and listened for the answer, Napoleon Hill, is now counted in the top ranks of the world\'s winners himself. The most famous of all teachers of success spent \"a fortune and the better part of a lifetime of effort\" to produce the \"Law of Success\" philosophy that forms the basis of his books and that is so powerfully summarized in this one. In the original Think and Grow Rich, published in 1937, Hill draws on stories of Andrew Carnegie, Thomas Edison, Henry Ford, and other millionaires of his generation to illustrate his principles. In the updated version, Arthur R. Pell, Ph.D., a nationally known author, lecturer, and consultant in human resources management and an expert in applying Hill\'s thought, deftly interweaves anecdotes of how contemporary millionaires and billionaires, such as Bill Gates, Mary Kay Ash, Dave Thomas, and Sir John Templeton, achieved their wealth. Outmoded or arcane terminology and examples are faithfully refreshed to preclude any stumbling blocks to a new generation of readers.', 'think-and-grow-rich_napoleon-hill_august-gold.jpg', '6.49'),
(20, 3, 'Fast Food Nation : The Dark Side of the All-American Meal', 'In hisNew York Times bestseller, National Magazine Award-winning journalist Eric Schlosser charts the fast food industry\'s enormous impact on our health, landscape, economy, politics and culture as he transforms the way America thinks about what it eats.', 'fast-food-nation-the-dark-side-of-the-all-american-meal-by-eric-schlosser.jpg', '4.79'),
(21, 3, 'Naked Economics : Undressing the Dismal Science', 'Finally! A book about economics that won\'t put you to sleep. In fact, you won\'t be able to put this bestseller down. In our challenging economic climate, this perennial favorite of students and general readers is more than a good read, it\'s a necessary investment--with a blessedly sure rate of return. Demystifying buzzwords, laying bare the truths behind oft-quoted numbers, and answering the questions you were always too embarrassed to ask, the breezy Naked Economics gives readers the tools they need to engage with pleasure and confidence in the deeply relevant, not so dismal science.This revised and updated edition adds commentary on hot topics, including the current economic crisis, globalization, the economics of information, the intersection of economics and politics, and the history--and future--of the Federal Reserve.', 'naked-economics-undressing-the-dismal-science-by-charles-wheelan.jpg', '4.79'),
(22, 3, 'Do What You Are', 'This guide analyzes personality type by looking at how an individual processes information, makes decisions and interacts with the world around them, and shows which of the 16 types describes that person best. It then lists dozens of occupations that are popular with people of each type and, using workbook exercises and real-life examples to highlight the strengths and pitfalls of each personality type, gives step-by-step instructions on how to use your unique strengths to customize your job search, ensuring the best results in the shortest period of time.', 'do-what-you-are--discover-the-perfect-career-for-you-through-the-secrets-of-personality.jpg', '4.69'),
(23, 4, 'If You Give a Mouse a Cookie', '\"If you give a mouse a cookie, he\'s going to ask for a glass of milk. When you give him the milk, he\'ll probably ask you for a straw. . . \". So begins this delightful story about an energetic mouse and an accommodating little boy. Full-color illustrations.', 'if-you-give-a-mouse-a-cookie-by-laura-joffe-numeroff.jpg', '4.79'),
(24, 4, 'Hatchet', 'This award-winning contemporary classic is the survival story with which all others are compared--and a page-turning, heart-stopping adventure, recipient of the Newbery Honor. Hatchet has also been nominated as one of America\'s best-loved novels by PBS\'s The Great American Read. Thirteen-year-old Brian Robeson, haunted by his secret knowledge of his mother\'s infidelity, is traveling by single-engine plane to visit his father for the first time since the divorce. When the plane crashes, killing the pilot, the sole survivor is Brian. He is alone in the Canadian wilderness with nothing but his clothing, a tattered windbreaker, and the hatchet his mother had given him as a present. At first consumed by despair and self-pity, Brian slowly learns survival skills--how to make a shelter for himself, how to hunt and fish and forage for food, how to make a fire--and even finds the courage to start over from scratch when a tornado ravages his campsite. When Brian is finally rescued after fifty-four days in the wild, he emerges from his ordeal with new patience and maturity, and a greater understanding of himself and his parents.', 'hatchet_gary-paulsen.jpg', '4.69'),
(25, 4, 'Oh, The Thinks You Can Think', 'From dreamy thoughts about colour to fantastic notions on left and right, this surreal book encourages young children to let their imaginations run riot and think up all kinds of weird and wonderful things. This delightful beginner book now joins 16 of dr. Seuss\' most popular works in the classic collection series, which also contains the cat in the hat, fox in socks and green eggs and ham. With dr. Seuss\' usual measure of riotous rhyme and wacky illustrations it will encourage even the most reluctant child to learn to read. With his unique combination of hilarious stories, zany pictures and riotous rhymes, dr. Seuss has been delighting young children and helping them learn to read for over fifty years. Creator of the wonderfully anarchic cat in the hat, and ranking among the uk\'s top ten favourite children\'s authors, seuss is firmly established as a global best-seller, with nearly half a million books sold worldwide. This delightful book forms part of the third stage in harpercollins\' major dr. Seuss rebrand programme. With the relaunch of six more titles in january 2004, such all-time favourites as the lorax, the foot book and yertle the turtle boast bright new covers that incorporate much needed guidance on reading levels: blue back books are for parents to share with young children, green back books are for budding readers to tackle on their own, and yellow back books are for older, more fluent readers to enjoy. Oh the thinks you can think! belongs to the green back book range.', 'oh-the-thinks-you-can-think-green-back-book-by-dr-seuss.jpg', '10.19'),
(26, 5, 'The Indispensable Calvin & Hobbes', 'Calvin, the six-year-old dirty tricksmeister and master of indignation and his warm, cuddly philosopher sidekick and Hobbes, a tiger whose idea of adventure is to lie on his back by the fire and have his stomach rubbed. This unlikely due captured the hearts, the minds, and, most of all, the funny bones of America. The Indispensable Calvin and Hobbes contains an original full-color section, as well as all the cartoons appearing in The Revenge of the Baby-Sat and Scientific Progress Goes \"Boink.\" All Sunday cartoons are presented in full-color.', 'the-indispensable-calvin-and-hobbes_bill-watterson.jpg', '4.79'),
(27, 5, 'Troublemaker', 'Alex Barnaby and Sam Hooker are back together and fighting crime the only way they know how by leaving a trail of chaos, panic, and disorder. Alex is an auto mechanic and spotter for racecar driver Sam Hooker. Unfortunately, she\'s also drawn to Hooker in the same fashion. There\'s no steering clear of trouble or Hooker when friends Rosa and Felicia call for help. A man has gone missing, and in order to find him Barnaby and Hooker will have to go deep into the underbelly of Miami and southern Florida.', 'troublemaker-by-janet-evanovich-alex-evanovich.jpg', '4.69'),
(28, 5, 'Watchmen', 'A new TV series based on Watchmen will debut on HBO in 2019 by the creator of Lost, Damon Lindelof A murder mystery-turned-nationwide conspiracy, WATCHMEN examines the lives of the eponymous superhero team as they seem to decay alongside the ever-darkening America around them. Rorschach, Nite Owl, the Silk Spectre, Dr. Manhattan and Ozymandias reunite to investigate who\'s behind a teammate\'s murder, but find that the truth may be even more grim than the world they seek to protect. One of the most influential graphic novels of all time and a perennial bestseller, WATCHMEN is considered a gateway title to the entire graphic storytelling medium. Alan Moore and Dave Gibbons\' seminal story is the benchmark against which all other graphic novels and comic books are judged with an incredible story that chronicles the fall from grace of a group of super-heroes plagued by all-too-human failings. This edition of WATCHMEN, the groundbreaking series from Alan Moore, the award-winning writer of V FOR VENDETTA and BATMAN: THE KILLING JOKE, and Dave Gibbons, the artist of GREEN LANTERN, features the high-quality, recolored pages found in WATCHMEN: THE ABSOLUTE EDITION with sketches, never-before-seen extra bonus materials and a new introduction by Dave Gibbons.', 'watchmen-by-alan-moore.jpg', '26.09'),
(29, 5, 'Fruits Basket', 'No Synopsis Available.', 'fruits-basket-volume-1_natsuki-takaya.jpg', '4.59'),
(30, 6, 'Adobe Photoshop CS3 for Photographers', 'Master the power of Photoshop CS3 with an internationally renowned photographer by your side.Adobe\'s Photoshop CS3 comes with powerful new features with huge payoffs. But it can be overwhelming to learn, even for professional photographers, graphic designers, keen amateurs, and others who already have an initial grasp of Photoshop. Acclaimed photographer Martin Evening, who wrote the best-selling previous books, \'Adobe Photoshop for Photographers\', makes it easy with this new, thoroughly updated edition. * Illustrated throughout with before-and-after pictures - more than 750 professional, color illustrations * Practical techniques and real-life assignments* Step-by-step tutorials* Keyboard shortcut reference guideIncludes FREE DVD with: * QuickTime movie tutorials for MAC and PC * Searchable tips on tools, palettes layer styles, and shortcuts * Includes images selected for you to experiment with to get you up to speed with everything in the book, including the new Photoshop CS3 features, fast * Updated Camera Guide to help you decide which will best suit your needs, plus bonus Digital Capture chapter in printable PDF formatUncover quickly exactly what Adobe\'s CS3 now offers photographers. New tutorials focus on the key features introduced in CS3. You lose no time in finding out how to put your ideas to work with: * Adobe\'s Camera Raw 4 plug-in that can now also process TIFFs and JPEGs* New Align controls for combining HDR images; Photomerge; new Clone Stamp; Curves dialog that now incorporates Levels functionality; and improved controls for Brightness/Contrast to match raw image processing controls* The latest on Black and White adjustment, which provides all the black and white conversion tools you need for optimum monochrome conversions* A pro\'s scoop on choosing from among dozens of Photoshop\'s image adjustment methods to get the results you want* Tips on Bridge 2.0 and Lightroom - when you should use each* Top tactics for successful composite images, insider guidance on editing shadows and highlight adjustments, and lessons on how to preview and re-edit filter effects as many times as you want - without complex workaroundsGet the preeminent advice from one photographer to another as Martin completely updates you on the core aspects of working with Photoshop, digital workflow, and improving accessibility. Real-life examples, diagrams, illustrations, and step-by-step explanations ensure that you\'re up to speed with the next generation of digital photography in no time Foreword by Adobe Systems\' key Director of Engineering, Digital Imaging, Marc Pawliger', 'adobe-photoshop-cs3-for-photographers.jpg', '4.79'),
(31, 6, 'CNC Programming Handbook', 'Over its first two editions, this best-selling book has become the de facto standard for training and reference material at all levels of CNC programming. Used in hundreds of educational institutions around the world as the primary text for CNC courses, and used daily by many in-field CNC programmers and machine operators, this book literally defines CNC programming. Written with careful attention to detail, there are no compromises. Many of the changes in this new Third Edition are the direct result of comments and suggestions received from many CNC professionals in the field. This extraordinarily comprehensive work continues to be packed with over one thousand illustrations, tables, formulas, tips, shortcuts, and practical examples. The enclosed CD-ROM now contains a fully functional 15-day shareware version of CNC tool path editor/simulator, NCPlot(tm). This powerful, easy-to-learn software includes an amazing array of features, many not found in competitive products. NCPlot offers an unmatched combination of simplicity of use and richness of features. Support for many advanced control options is standard, including a macro interpreter that simulates Fanuc and similar macro programs. The CD-ROM also offers many training exercises based on individual chapters, along with solutions and detailed explanations. Special programming and machining examples are provided as well, in form of complete machine files, useful as actual programming resources. Virtually all files use Adobe PDF format and are set to high resolution printing. FEATURES Fully functional shareware version of CNC toolpath simulator/editor, NCPlot(TM), included on the CD-ROM. This powerful software includes an amazing array of features, including those not found in competitive products. Support for many advanced features is standard, and the included macro interpreter can simulate Fanuc and compatible macro toolpath programs Detailed section on CNC lathes with live tooling, including examples Image files of many actual parts, used as examples More programming examples (both in printed text and on the CD-ROM) Optimized for the latest Fanuc and related control systems Additional formulas, calculations and handy reference material Fourth axis programming (indexing and rotary) CD-ROM based projects, including several as interactive PDF forms Improved index for better search of topics', 'cnc-programming-handbook_peter-smid.jpg', '73.58'),
(32, 6, 'UNIX Network Programming', 'The leading book in its field, this guide focuses on the design, development and coding of network software under the UNIX operating system. Provides over 15,000 lines of C code with descriptions of how and why a given solution is achieved. For programmers seeking an indepth tutorial on sockets, transport level interface (TLI), interprocess communications (IPC) facilities under System V and BSD UNIX.', 'unix-network-programming_w-richard-stevens.jpg', '4.69'),
(33, 6, 'Head First Java', 'Learning a complex new language is no easy task especially when it s an object-oriented computer programming language like Java. You might think the problem is your brain. It seems to have a mind of its own, a mind that doesn\'t always want to take in the dry, technical stuff you\'re forced to study. The fact is your brain craves novelty. It\'s constantly searching, scanning, waiting for something unusual to happen. After all, that\'s the way it was built to help you stay alive. It takes all the routine, ordinary, dull stuff and filters it to the background so it won\'t interfere with your brain\'s real work--recording things that matter. How does your brain know what matters? It\'s like the creators of the Head First approach say, suppose you\'re out for a hike and a tiger jumps in front of you, what happens in your brain? Neurons fire. Emotions crank up. Chemicals surge. That\'s how your brain knows. And that\'s how your brain will learn Java. Head First Java combines puzzles, strong visuals, mysteries, and soul-searching interviews with famous Java objects to engage you in many different ways. It\'s fast, it\'s fun, and it\'s effective. And, despite its playful appearance, Head First Java is serious stuff: a complete introduction to object-oriented programming and Java. You\'ll learn everything from the fundamentals to advanced topics, including threads, network sockets, and distributed programming with RMI. And the new. second edition focuses on Java 5.0, the latest version of the Java language and development platform. Because Java 5.0 is a major update to the platform, with deep, code-level changes, even more careful study and implementation is required. So learning the Head First way is more important than ever. If you\'ve read a Head First book, you know what to expect--a visually rich format designed for the way your brain works. If you haven\'t, you\'re in for a treat. You\'ll see why people say it\'s unlike any other Java book you\'ve ever read. By exploiting how your brain works, Head First Java compresses the time it takes to learn and retain--complex information. Its unique approach not only shows you what you need to know about Java syntax, it teaches you to think like a Java programmer. If you want to be bored, buy some other book. But if you want to understand Java, this book\'s for you.', 'head-first-java_kathy-sierra_bert-bates.jpg', '15.09'),
(34, 6, 'The Data Warehouse Toolkit', '\". . . one of the definitive books of our industry. If you take the time to read only one professional book, make it this book.\" -W. H. Inmon One of the most dramatic new developments in database design, the dimensional data warehouse is a powerful database model that.significantly enhances managers\' ability to quickly analyze large, multidimensional data sets. Written by the leading proponent of this revolutionary new approach, this valuable book/CD toolkit outfits you with all the nuts-and-bolts information you need to design, build, manage, and use dimensional data warehouses for virtually any type of business application, as well as software for querying dimensional data warehouses. Employing many real-life case studies of data warehouses, Ralph Kimball provides clear-cut guidelines on how to model data and design data warehouses to support advanced multidimensional decision support systems. Beginning with the relatively simple example of a data warehouse for a grocery store, he progresses, step-by-step, through an increasingly complex array of business applications in retail, manufacturing, banking, insurance, subscriptions, and airline reservations. By the end of the book, you will have mastered the full range of powerful techniques for creating, controlling, and navigating dimensional business databases that are easy to understand and navigate. On the CD-ROM you\'ll find: * Software for querying dimensional data warehouses. * Working models of all the databases described in the book.', 'the-data-warehouse-toolkit.jpg', '4.69'),
(35, 7, 'Rose\'s Christmas Cookies', 'Since its 1990 publication, Rose\'s Christmas Cookies has been a phenomenal success. Who can resist Chocolate-Dipped Melting Moments Cookies or moist Mini-Cheesecakes with Lemon Curd . . . or David Shamah\'s Jumbles, a fabulous cross between a chocolate-chip cookie and a chunky candy bar bursting with raisins, chocolate chips, and pecans. Whether you need a cookie to decorate your tree or grace your mantelpiece (cookies like Stained Glass or Christmas Wreaths), a sweet to send (Mahogany Butter Crunch Toffee, Maple Macadamia Bars), or a special holiday treat for your dinner party (Praline Truffle Cups, Chocolate-Pistachio Marzipan Spirals), you\'ll find that perfect something here. Complete with 60 cookie recipes and a color photograph of each cookie for handy reference, this easy-to-use and fun-to-read book will result in scrumptious, festive, and splendid-looking cookies every time.', 'roses-christmas-cookies.jpg', '8.59'),
(36, 7, 'The Barbecue! Bible', 'Now the biggest and the best recipe collection for the grill is getting better: Announcing the full-color edition of The Barbecue Bible , the 900,000-copy bestseller and winner of the IACP/Julia Child Cookbook Award. Redesigned inside and out for its 10th anniversary, The Barbecue Bible now includes full-color photographs illustrating food preparation, grilling techniques, ingredients, and of course those irresistible finished dishes. A new section has been added with answers to the most frequently asked grilling questions, plus Steven\'s proven tips, quick solutions to common mistakes, and more. And then there\'s the literal meat of the book: more than 500 of the very best barbecue recipes, inventive, delicious, unexpected, easy-to-make, and guaranteed to capture great grill flavors from around the world. Add in the full-color, and it\'s a true treasure.', 'the-barbecue-bible.jpg', '5.79'),
(37, 7, 'Mary Bell\'s Complete Dehydrator Cookbook', 'Far from being a fad, food dyhydrating is one of the most ancient, effective, and nutritous ways of preserving food. Now, at last, there is a book that teaches absolutely everything there is to know about using an electric food dyhydrator to dry foods at home -- and gives more than 100 foolproof recipes for scrumptious snacks and meals made from dried foods. With this extraordinary book, you can learn how to cross junk food and expensive store-bought snacks off your family\'s shopping list -- and add to your cupboard homemade, preservative-free fruit leathers, candied apricots, beef (and fish) jerkies, \"sun\" dried tomotoes, corn chips, banana chips, and so much more Mary Bell gives specific techniques and instructions for preparing every kind of fruit (from apples to watermelon) and vegetable (from asparagus to zucchini). She also provides important shopping tips for buying an electric food dehydrator. The recipes for cooked meals (including mushroom soup, sloppy joes, pesto, and moist banana bread) will make this book a kitchen classic. And recipes for lightweight, filling trail snacks mean that the book will travel, too. Additional chapters explain to how make herb seasonings, granolas, celery powder, cosmetics, dried fruit sugars, potpourri -- and even pet treats Food drying is an excellent way for gardeners to preserve their produce. It is a great way to make healthful snacks for the kids. It\'s perfect for the new wave of thrifty consumers who can\'t bear to spend dollars at health food stores for treats they cold make for pennies themselves. And food drying doesn\'t use chemicals or preservatives--so it\'s great for you and for the planet, too', 'complete-dehydrator-cookbook.jpg', '4.69'),
(38, 7, 'Martha Stewart\'s Cooking School', 'Imagine having Martha Stewart at your side in the kitchen, teaching you how to hold a chefâ€™s knife, select the very best ingredients, truss a chicken, make a perfect pot roast, prepare every vegetable, bake a flawless pie crust, and much more.In Martha Stewartâ€™s Cooking School, you get just that: a culinary master class from Martha herself, with lessons for home cooks of all levels.Never before has Martha written a book quite like this one. Arranged by cooking technique, itâ€™s aimed at teaching you how to cook, not simply what to cook. Delve in and soon youâ€™ll be roasting, broiling, braising, stewing, sautÃ©ing, steaming, and poaching with confidence and competence. In addition to the techniques, youâ€™ll find more than 200 sumptuous, all-new recipes that put the lessons to work, along with invaluable step-by-step photographs to take the guesswork out of cooking. Youâ€™ll also gain valuable insight into equipment, ingredients, and every other aspect of the kitchen to round out your culinary education.Featuring more than 500 gorgeous color photographs, Martha Stewartâ€™s Cooking School is the new gold standard for everyone who truly wants to know his or her way around the kitchen. This best-selling cookbook originally inspired Martha Stewart\'s beloved PBS series of the same name and includes some of the recipes the show featured in its first seasons.', 'martha-stewarts-cooking-school-lessons-and-recipes-for-the-home-cook.jpg', '8.69'),
(39, 7, 'Ben and Jerry\'s Homemade Ice Cream and Dessert Book', 'With little skill, surprisingly few ingredients, and even the most unsophisticated of ice-cream makers, you can make the scrumptious ice creams that have made Ben & Jerry\'s an American legend. Ben & Jerry\'s Homemade Ice Cream & Dessert Book tells fans the story behind the company and the two men who built it-from their first meeting in 7th-grade gym class (they were already the two widest kids on the field) to their \"graduation\" from a $5.00 ice-cream-making correspondence course to their first ice-cream shop in a renovated gas station. But the best part comes next. Dastardly Mash, featuring nuts, raisins, and hunks of chocolate. The celebrated Heath Bar Crunch. New York Super Fudge Chunk. Oreo Mint. In addition to Ben & Jerry\'s 11 greatest hits, here are recipes for ice creams made with fresh fruit, with chocolate, with candies and cookies, and recipes for sorbets, sundaes, and baked goods.', 'ben--jerrys-homemade-ice-cream--dessert-book.jpg', '4.69'),
(40, 8, 'Kovels\' New Dictionary of Marks', 'You may be the owner of a valuable piece of porcelain or pottery, but the cryptic symbol on the underside of the piece may be your only clue to its value. Kovels\' New Dictionary of Marks: 1850 to the Present will help you identify your pieces.Kovels\' New Dictionary of Marks provides the quickest and easiest way for professional and amateur collectors to identify more than 3,500 American, European, and Oriental marks. The perfect companion to the Kovels\' original best-seller, Kovels\' Dictionary of Marks -- Pottery and Porcelain: 1650 to 1850 (still in print after more than 42 years and 41 printings), Kovels\' New Dictionary of Marks is the most comprehensive reference for nineteenth- and twentieth-century marks. Together, the two volumes are an indispensable guide to porcelain and pottery marks of the last four centuries.Also available from Three Rivers Press, Kovels\' Dictionary of Marks--Pottery & Porcelain: 1650 to 1850', 'kovels-new-dictionary-of-marks.jpg', '4.69'),
(41, 8, 'The Book of Kells', 'The Book of Kells is a masterpiece of medieval art--a brilliantly decorated version of the four Gospels with full-page depictions of Christ, the Virgin and the Evangelists as well as a wealth of smaller decorative painting. The strange imagination displayed in the pages, the impeccable technique and the very fine state of preservation make The Book of Kells an object of endless fascination. This edition reproduces the most important of the fully decorated pages plus a series of enlargements showing the almost unbelievable minuteness of the detail; spiral and interlaced patterns, human and animal ornament--a combination of high seriousness and humor. The text is by Bernard Meehan, the Keeper of Manuscripts at Trinity College, Dublin.', 'the-book-of-kells.jpg', '4.69'),
(42, 8, 'Generation T : 108 Ways to Transform a T-Shirt', 'Make it yours. This inspirational guide with DIY attitude has everything you need to know about the world\'s great T-shirt: how to cut it, sew it, deconstruct it, reconstruct it, and best of all, transform it. Features more than 100 projects (plus 200 variations) for customized tees, tank tops, tube tops, T-skirtseven handbags, a patchwork blanket, iPod cozies, leg warmers, and more. Not a DIY expert? Not to worry. More than one third of the projects are no sew, meaning anyone who can wield a pair of scissors can put a personal stamp on her wardrobe. But the sewing basics are here too: backstitch and whipstitch, gather and ruche, appliqu? and drawstrings. And the mission statement for Generation T : Ask not what your T-shirt can do for you; ask what you can do for your T-shirt. And then Do-It-Yourself!', 'generation-t-108-ways-to-transform-a-t-shirt.jpg', '4.79'),
(43, 8, 'Making Bead and Wire Jewelry', '75 stunning pieces of jewellery, made of beads and wire, requiring only a few simple tools and easy-to-learn techniques. The projects include: - earrings - necklaces - bracelets - pendants - a contemporary eyeglass chain - - hair clip - filigree choker - finger rings - pins - eyeglass cord - There are complete instructions on bead and wire crafting basics; materials, tips and techniques, tools and work spaces are all thoroughly covered. * Two best-selling craft subjects - bead jewellery and wire jewellery - together in one book. * Styles range from the delicate and graceful to bold and chunky. * Beads range from small delicate crystals to large brilliant pieces of turquoise. * Wire includes the new wires currently available, textured and dyed every colour of the rainbow, plus copper, gold and silver options.', 'making-bead--wire-jewelry-simple-techniques-stunning-designs.jpg', '4.79'),
(44, 9, 'International Residential Code 2003', 'The 2003 International Residential Code brings uniformity to construction of one- and two-family dwellings and townhouses up to three stories high. A comprehensive code for homebuilding, this book brings together all building, plumbing, mechanical, and electrical provisions for one- and two-family residences. It establishes minimum regulations using prescriptive provisions, and is founded on broad-based principles that make possible the use of new materials and building designs. This 2003 edition is fully compatible with all the International Codes published by the International Code Council (ICC).', 'international-residential-code.jpg', '6.09'),
(45, 9, 'What Your Fifth Grader Needs to Know', 'No Synopsis Available.', 'what-your-fifth-grader-needs-to-know.jpg', '4.79'),
(46, 9, 'Merriam-Webster\'s Spanish-English Dictionary', 'A bilingual, bi-directional guide to Spanish and American English with extensive coverage of Latin-American Spanish. More than 80,000 entries and 100,000 translations. Abundant examples of words used in context.', 'merriam-websters-spanish-english-dictionary.jpg', '4.79'),
(47, 9, 'They Say / I Say : The Moves That Matter in Academic Writing', '\"They Say / I Say\" shows that writing well means mastering some key rhetorical moves, the most important of which involves summarizing what others have said (\"they say\") to set up one\'s own argument (\"I say\"). In addition to explaining the basic moves, this book provides writing templates that show students explicitly how to make these moves in their own writing.', 'they-sayi-say-the-moves-that-matter-in-academic-writing.jpg', '4.79'),
(48, 10, 'Understanding the Borderline Mother', 'Some readers may recognize their mothers as well as themselves in this book. They will also find specific suggestions for creating healthier relationships. Addressing the adult children of borderlines and the therapists who work with them, Dr. Lawson shows how to care for the waif without rescuing her, to attend to the hermit without feeding her fear, to love the queen without becoming her subject, and to live with the witch without becoming her victim.', 'understanding-the-borderline-mother.jpg', '34.69'),
(49, 10, 'The Miracle of Mindfulness : A Manual on Meditation', 'Exercises in active and passive Zen meditation are accompanied by a discussion of their relevance in contemporary living.\"', 'the-miracle-of-mindfulness.jpg', '4.79'),
(50, 10, 'The New Encyclopedia of Modern Bodybuilding', 'From elite bodybuilding competitors to gymnasts, from golfers to fitness gurus, anyone who works out with weights must own this bookâ€”a book that only Arnold Schwarzenegger could write, a book that has earned its reputation as â€œthe bible of bodybuilding.â€Inside, Arnold covers the very latest advances in both weight training and bodybuilding competition, with new sections on diet and nutrition, sports psychology, the treatment and prevention of injuries, and methods of training, each illustrated with detailed photos of some of bodybuilding\'s newest stars. Plus, all the features that have made this book a classic are here: -Arnold\'s tried-and-true tips for sculpting, strengthening, and defining each and every muscle to create the ultimate buff physique -The most effective methods of strength training to stilt your needs, whether you\'re an amateur athlete or a pro bodybuilder preparing for a competition -Comprehensive information on health, nutrition, and dietary supplements to help you build muscle, lose fat, and maintain optimum energy -Expert advice on the prevention and treatment of sports-related injuries -Strategies and tactics for competitive bodybuilders from selecting poses to handling publicity -The fascinating history and growth of bodybuilding as a sport, with a photographic â€œBodybuilding Hall of Fameâ€ -And, of course, Arnold\'s individual brand of inspiration and motivation throughout Covering every level of expertise and experience, The New Encyclopedia of Modern Bodybuilding will help you achieve your personal best. With his unique perspective as a seven-time winner of the Mr. Olympia title and all international film star, Arnold shares his secrets to dedication, training, and commitment, and shows you how to take control of your body and realize your own potential for greatness.', 'the-new-encyclopedia-of-modern-bodybuilding.jpg', '15.59'),
(51, 10, 'The No-Cry Sleep Solution', 'A breakthrough approach for a good night\'s sleep--with no tears There are two schools of thought for encouraging babies to sleep through the night: the hotly debated Ferber technique of letting the baby \"cry it out,\" or the grin-and-bear-it solution of getting up from dusk to dawn as often as necessary. If you don\'t believe in letting your baby cry it out, but desperately want to sleep, there is now a third option, presented in Elizabeth Pantley\'s sanity-saving book The No-Cry Sleep Solution . Pantley\'s successful solution has been tested and proven effective by scores of mothers and their babies from across the United States, Canada, and Europe. Based on her research, Pantley\'s guide provides you with effective strategies to overcoming naptime and nighttime problems. The No-Cry Sleep Solution offers clearly explained, step-by-step ideas that steer your little ones toward a good night\'s sleep--all with no crying. Tips from The No-Cry Sleep Solution: Uncover the stumbling blocks that prevent baby from sleeping through the night Determine--and work with--baby\'s biological sleep rhythms Create a customized, step-by-step plan to get baby to sleep through the night Use the Persistent Gentle Removal System to teach baby to fall asleep without breast-feeding, bottlefeeding, or using a pacifier', 'the-no-cry-sleep-solution.jpg', '4.79'),
(52, 10, 'The Trigger Point Therapy Workbook', 'This is a useful book for anyone in chronic pain. There are few resources like this one, which empowers the reader to understand the problem and offers the tools to manage it.', 'the-trigger-point-therapy-workbook.jpg', '4.69'),
(53, 11, 'Persepolis : The Story of a Childhood', 'A New York Times Notable Book A Time Magazine \"Best Comix of the Year\" A San Francisco Chronicle and Los Angeles Times Best-seller Wise, funny, and heartbreaking, Persepolis is Marjane Satrapi\'s graphic memoir of growing up in Iran during the Islamic Revolution. In powerful black-and-white comic strip images, Satrapi tells the story of her life in Tehran from ages six to fourteen, years that saw the overthrow of the Shah\'s regime, the triumph of the Islamic Revolution, and the devastating effects of war with Iraq. The intelligent and outspoken only child of committed Marxists and the great-granddaughter of one of Iran\'s last emperors, Marjane bears witness to a childhood uniquely entwined with the history of her country. Persepolis paints an unforgettable portrait of daily life in Iran and of the bewildering contradictions between home life and public life. Marjane\'s child\'s-eye view of dethroned emperors, state-sanctioned whippings, and heroes of the revolution allows us to learn as she does the history of this fascinating country and of her own extraordinary family. Intensely personal, profoundly political, and wholly original, Persepolis is at once a story of growing up and a reminder of the human cost of war and political repression. It shows how we carry on, with laughter and tears, in the face of absurdity. And, finally, it introduces us to an irresistible little girl with whom we cannot help but fall in love.', 'persepolis-the-story-of-a-childhood.jpg', '4.79'),
(54, 11, 'Killing Kennedy : The End of Camelot', 'A riveting historical narrative of the shocking events surrounding the assassination of John F. Kennedy. In this #1 New York Times Bestseller, the anchor of The O\'Reilly Factor recounts in gripping detail the brutal murder of John Fitzgerald Kennedy - and how a sequence of gunshots on a Dallas afternoon not only killed a beloved president but also sent the nation into the cataclysmic division of the Vietnam War and its culture-changing aftermath. In January 1961, as the Cold War escalates, John F. Kennedy struggles to contain the growth of Communism while he learns the hardships, solitude, and temptations of what it means to be president of the United States. Along the way he acquires a number of formidable enemies, among them Soviet leader Nikita Khrushchev, Cuban dictator Fidel Castro, and Alan Dulles, director of the C.I.A. In addition, powerful elements of organized crime have begun to talk about targeting the president and hisbrother, Attorney General Robert Kennedy. In the midst of a 1963 campaign trip to Texas, Kennedy is gunned down by an erratic young drifter named Lee Harvey Oswald. The former Marine Corps sharpshooter escapes the scene, only to be caught and shot dead while in police custody. The events leading up to the most notorious crime of the twentieth century are almost as shocking as the assassination itself. Killing Kennedy chronicles both the heroism and deceit of Camelot, bringing history to life in ways that will profoundly move the reader. This may well be the most talked about book of the year.', 'killing-kennedy_bill-oreilly.jpg', '4.19'),
(55, 11, 'Black Elk Speaks', 'Named one of the ten best spiritual books of the twentieth century by Philip Zaleski of HarperSanFrancisco, Black Elk Speaks is the acclaimed story of Lakota visionary and healer Nicholas Black Elk (1863-1950) and his people during the momentous, twilight years of the nineteenth century. Black Elk grew up in a time when white settlers were invading the Lakotas\' homeland, decimating buffalo herds and threatening to extinguish the Lakotas\' way of life. Black Elk and other Lakotas fought back, a dogged resistance that resulted in a remarkable victory at the Little Bighorn and an unspeakable tragedy at Wounded Knee. Beautifully told by the celebrated poet and writer John G. Neihardt, Black Elk Speaks offers much more than a life story. Black Elk\'s profound and arresting religious visions of the unity of humanity and the world around him have transformed his account into a venerated spiritual classic. Whether appreciated as a collaborative autobiography, a history of a Native American nation, or an enduring spiritual testament for all humankind, Black Elk Speaks is unforgettable. This special edition features all three prefaces to Black Elk Speaks that John G. Neihardt wrote at different points in his life, a map of Black Elk\'s world, a reset text, a listing of Lakota words newly translated and reproduced using the latest orthographic standards, and color paintings by Lakota artist Standing Bear that have not been widely available for decades.', 'black-elk-speaks.jpg', '4.69'),
(56, 12, 'Decks 1-2-3', 'No Synopsis Available.', 'decks-1-2-3.jpg', '4.79');
INSERT INTO `products` (`id`, `category_id`, `title`, `description`, `image`, `price`) VALUES
(57, 12, 'Gardening When It Counts : Growing Food in Hard Times', 'Discover forgotten low-input food gardening methods for surviving uncertain times ahead. The decline of cheap oil is inspiring increasing numbers of North Americans to achieve some measure of backyard food self-sufficiency. In hard times, the family can be greatly helped by growing a highly productive food garden, requiring little cash outlay or watering. Currently popular intensive vegetable gardening methods are largely inappropriate to this new circumstance. Crowded raised beds require high inputs of water, fertility and organic matter, and demand large amounts of human time and effort. But, except for labor, these inputs depend on the price of oil. Prior to the 1970s, North American home food growing used more land with less labor, with wider plant spacing, with less or no irrigation, and all done with sharp hand tools. But these sustainable systems have been largely forgotten. Gardening When It Counts helps readers rediscover traditional low-input gardening methods to produce healthy food. Designed for readers with no experience and applicable to most areas in the English-speaking world except the tropics and hot deserts, this book shows that any family with access to 3-5,000 sq. ft. of garden land can halve their food costs using a growing system requiring just the odd bucketful of household waste water, perhaps two hundred dollars worth of hand tools, and about the same amount spent on supplies-working an average of two hours a day during the growing season. Mother Earth News Wiser Living Series', 'gardening-when-it-counts.jpg', '19.30'),
(58, 12, 'Parenting from the Inside Out', 'How many parents have found themselves thinking: I can\'t believe I just said to my child the very thing my parents used to say to me Am I just destined to repeat the mistakes of my parents? In Parenting from the Inside Out , child psychiatrist Daniel J. Siegel, M.D., and early childhood expert Mary Hartzell, M.Ed., explore the extent to which our childhood experiences actually do shape the way we parent. Drawing upon stunning new findings in neurobiology and attachment research, they explain how interpersonal relationships directly impact the development of the brain, and offer parents a step-by-step approach to forming a deeper understanding of their own life stories, which will help them raise compassionate and resilient children. Born out of a series of parents\' workshops that combined Siegel\'s cutting-edge research on how communication impacts brain development with Hartzell\'s thirty years of experience as a child-development specialist and parent educator, Parenting from the Inside Out guides parents through creating the necessary foundations for loving and secure relationships with their children.', 'parenting-from-the-inside-out.jpg', '4.69'),
(59, 13, 'odd interlude', 'No Synopsis Available.', 'odd-interlude-a-special-odd-thomas-adventure.jpg', '9.59'),
(60, 13, 'The Zombie Survival Guide : Recorded Attacks', 'Those who don t learn from history are condemned to repeat it. From the Stone Age to the information age, the undead have threatened to engulf the human race. They re coming. They re hungry. Don t wait for them to come to you This is the graphic novel the fans demanded: major zombie attacks from the dawn of humanity. On the African savannas, against the legions of ancient Rome, on the high seas with Francis Drake . . . every civilization has faced them. Here are the grisly and heroic stories complete with eye-popping artwork that pulsates with the hideous faces of the undead. Organize before they rise Scripted by the world s leading zombie authority, Max Brooks, Recorded Attacks reveals how other eras and cultures have dealt with and survived the ancient viral plague. By immersing ourselves in past horror we may yet prevail over the coming outbreak in our time.\"', 'the-zombie-survival-guide-recorded-attacks.jpg', '4.79'),
(61, 14, 'Is Everyone Hanging Out Without Me? : (And Other Concerns)', 'Mindy Kaling has lived many lives: the obedient child of immigrant professionals, a timid chubster afraid of her own bike, a Ben Affleck-impersonating Off-Broadway performer and playwright, and, finally, a comedy writer and actress prone to starting fights with her friends and coworkers with the sentence \"Can I just say one last thing about this, and then I swear I\'ll shut up about it?\" Perhaps you want to know what Mindy thinks makes a great best friend (someone who will fill your prescription in the middle of the night), or what makes a great guy (one who is aware of all elderly people in any room at any time and acts accordingly), or what is the perfect amount of fame (so famous you can never get convicted of murder in a court of law), or how to maintain a trim figure (you will not find that information in these pages). If so, you\'ve come to the right book, mostly In Is Everyone Hanging Out Without Me?, Mindy invites readers on a tour of her life and her unscientific observations on romance, friendship, and Hollywood, with several conveniently placed stopping points for you to run errands and make phone calls. Mindy Kaling really is just a Girl Next Door--not so much literally anywhere in the continental United States, but definitely if you live in India or Sri Lanka. From the Hardcover edition.', 'is-everyone-hanging-out-without-me-and-other-concernsenhanced-edition.jpg', '4.69'),
(62, 14, 'The Ultimate Book of Optical Illusions', 'Prepare to be amazed! Inside the covers of this incredible, colorful collection are hundreds of the worldâ€™s most powerful optical illusions. Theyâ€™re beautiful to behold, and stunning in their trickery. Some of the mind-boggling images seem to spring into action, vibrating, pulsing, and spinning like a hula hoop. Other ambiguous illusions feature two subjects in one: the fun is in finding them both in the single pictureâ€”including a mouse playing hide and seek in a catâ€™s face and a strange desert mirage where palm trees imperceptibly morph into camels. And still more, like â€œThe Impossible Terrace,â€ which couldnâ€™t exist off the page: just try to figure out if youâ€™re viewing the space from above or below. Every one is astonishing.', 'the-ultimate-book-of-optical-illusions.jpg', '4.69'),
(63, 15, 'The Old Man and The Sea', 'The Old Man and the Sea is one of Hemingway\'s most enduring works. Told in language of great simplicity and power, it is the story of an old Cuban fisherman, down on his luck, and his supreme ordeal -- a relentless, agonizing battle with a giant marlin far out in the Gulf Stream. Here Hemingway recasts, in strikingly contemporary style, the classic theme of courage in the face of defeat, of personal triumph won from loss. Written in 1952, this hugely successful novella confirmed his power and presence in the literary world and played a large part in his winning the 1954 Nobel Prize for Literature.', 'the-old-man-and-the-sea.jpg', '4.69'),
(64, 15, 'A Game of Thrones (A Song of Ice and Fire, Book 1)', 'Long ago, in a time forgotten, a preternatural event threw the seasons out of balance. In a land where summers can last decades and winters a lifetime, trouble is brewing. The cold is returning, and in the frozen wastes to the north of Winterfell, sinister and supernatural forces are massing beyond the kingdomâ€™s protective Wall. At the center of the conflict lie the Starks of Winterfell, a family as harsh and unyielding as the land they were born to. Sweeping from a land of brutal cold to a distant summertime kingdom of epicurean plenty, here is a tale of lords and ladies, soldiers and sorcerers, assassins and bastards, who come together in a time of grim omens.Here an enigmatic band of warriors bear swords of no human metal; a tribe of fierce wildlings carry men off into madness; a cruel young dragon prince barters his sister to win back his throne; and a determined woman undertakes the most treacherous of journeys. Amid plots and counterplots, tragedy and betrayal, victory and terror, the fate of the Starks, their allies, and their enemies hangs perilously in the balance, as each endeavors to win that deadliest of conflicts: the game of thrones.Here is the first volume in George R. R. Martinâ€™s magnificent cycle of novels that includes A Clash of Kings and A Storm of Swords. As a whole, this series comprises a genuine masterpiece of modern fantasy, bringing together the best the genre has to offer. Magic, mystery, intrigue, romance, and adventure fill these pages and transport us to a world unlike any we have ever experienced. Already hailed as a classic, George R. R. Martinâ€™s stunning series is destined to stand as one of the great achievements of imaginative fiction.', 'a-game-of-thrones.jpg', '5.49'),
(65, 15, 'Mythology', 'The world-renowned classic that has enthralled and delighted millions of readers with its timeless tales of gods and heroes. Edith Hamilton\'s mythology succeeds like no other book in bringing to life for the modern reader the Greek, Roman and Norse myths that are the keystone of Western culture-the stories of gods and heroes that have inspired human creativity from antiquity to the present. We follow the drama of the Trojan War and the wanderings of Odysseus. We hear the tales of Jason and the Golden Fleece, Cupid and Psyche, and mighty King Midas. We discover the origins of the names of the constellations. And we recognize reference points for countless works for art, literature and culture inquiry-from Freud\'s Oedipus complex to Wagner\'s Ring Cycle of operas to Eugene O\'Neill\'s Mourning Becomes Electra Both a reference text for scholars of all ages and a book to simply enjoy, Mythology is a classic not to be missed.', 'mythology.jpg', '4.69'),
(66, 16, 'The Social Transformation of American Medicine', 'No Synopsis Available.', 'the-social-transformation-of-american-medicine.jpg', '4.69'),
(67, 16, 'Publication Manual', 'In addition to providing guidance on grammar, the mechanics of writing, and APA style, this manual offers an authoritative reference and citation system. It also covers the treatment of numbers, metrication, statistical and mathematical data, tables and figures for use in writing, reports or presentations.', 'publication-manual-of-the-american-psychological-association.jpg', '4.79'),
(68, 16, 'The Great Influenza', 'The definitive account of the 1918 Flu Epidemic. \"Monumental\"-Chicago Tribune. At the height of WWI, history\'s most lethal influenza virus erupted in an army camp in Kansas, moved east with American troops, then exploded, killing as many as 100 million people worldwide. It killed more people in twenty-four months than AIDS killed in twenty-four years, more in a year than the Black Death killed in a century. But this was not the Middle Ages, and 1918 marked the first collision of science and epidemic disease. Magisterial in its breadth of perspective and depth of research and now revised to reflect the growing danger of the avian flu, The Great Influenza is ultimately a tale of triumph amid tragedy, which provides us with a precise and sobering model as we confront the epidemics looming on our own horizon. John M. Barry has written a new afterword for this edition that brings us up to speed on the terrible threat of the avian flu and suggest ways in which we might head off another flu pandemic.', 'the-great-influenza-the-epic-story-of-the-deadliest-plague-in-history.jpg', '4.69'),
(69, 17, 'Breaking Point', 'Wyoming game warden Joe Pickett\'s hunt for a fugitive reveals a conspiracy in this taut thriller in the #1 New York Times bestselling series. Joe Pickett always liked Butch Roberson--a hardworking local business-owner whose daughter is friends with his own. Little does he know that when Butch says he is heading into the mountains to scout elk, he is actually going on the run. Two EPA employees have been murdered, and all signs point to Butch as the killer. Soon, Joe hears of the land Butch and his wife had bought to retire on--until they are told the EPA declared it a wetland--and the penalties they charged Butch until the family was torn apart by debt. Finally, it seems, the man just cracked. It\'s an awful story. But is it the whole story? The more Joe investigates, the more he begins to wonder--and the more he finds himself in the middle of a war in which he must choose sides.', 'breaking-point.jpg', '6.59'),
(70, 17, 'Along Came a Spider', 'Discover the classic thriller that launched the #1 detective series of the past twenty-five years, now one of PBS\'s \"100 Great American Reads\" Alex Cross is a homicide detective with a Ph.D. in psychology. He works and lives in the ghettos of D. C. and looks like Muhammad Ali in his prime. He\'s a tough guy from a tough part of town who wears Harris Tweed jackets and likes to relax by banging out Gershwin tunes on his baby grand piano. But he also has two adorable kids of his own, and they are his own special vulnerabilities. Jezzie Flanagan is the first woman ever to hold the highly sensitive job as supervisor of the Secret Service in Washington. Blond, mysterious, seductive, she\'s got an outer shell that\'s as tough as it is beautiful. She rides her black BMW motorcycle at speeds of no less than 100 mph. What is she running from? What is her secret? Alex Cross and Jezzie Flanagan are about to have a forbidden love affair-at the worst possible time for both of them. Because Gary Soneji, who wants to commit the \"crime of the century,\" is playing at the top of his game. Soneji has outsmarted the FBI, the Secret Service, and the police. Who will be his next victim? Gary Soneji is every parent\'s worst nightmare. He has become Alex Cross\'s nightmare. And now, reader, he\'s about to become yours.', 'along-came-a-spider.jpg', '6.19'),
(71, 17, 'Bad Luck and Trouble', '#1 NEW YORK TIMES BESTSELLER \"Electrifying . . . This series [is] utterly addictive.\" --Janet Maslin, The New York Times \"[An] action-packed thrill ride.\"-- Chicago Tribune From a helicopter high above the California desert, a man is sent free-falling into the night. On the streets of Portland, Jack Reacher is pulled out of his wandering life and plunged into the heart of a conspiracy that is killing old friends . . . and the people he once trusted with his life. Reacher is the ultimate loner--no phone, no ties, no address. But a woman from his old military unit has found him using a signal only the eight members of their elite team would know. Then she tells him a terrifying story about the brutal death a man they both served with. Soon Reacher is reuniting with the survivors of his team, scrambling to unravel the sudden disappearance of two other comrades. But Reacher won\'t give up--because in a world of bad luck and trouble, when someone targets Jack Reacher and his team, they\'d better be ready for what comes right back at them. \"A slam-bang yarn filled with Child\'s usual terse life-and-death lessons.\"-- Entertainment Weekly \"A breathless, ultra-cool novel with relentless pacing.\"-- The Plain Dealer \"Tension-packed . . . one of the most enjoyable of the Reacher thrillers.\"-- Orlando Sentinel', 'bad-luck-and-trouble.jpg', '5.99'),
(72, 18, 'Beautiful Boy', '#1 New York Times bestseller Now a Major Motion Picture Starring Steve Carell * Timoth e Chalamet * Maura Tierney * and Amy Ryan \"A brilliant, harrowing, heartbreaking, fascinating story, full of beautiful moments and hard-won wisdom. This book will save a lot of lives and heal a lot of hearts.\" -- Anne Lamott \"\'When one of us tells the truth, he makes it easier for all of us to open our hearts to our own pain and that of others.\' That\'s ultimately what Beautiful Boy is about: truth and healing.\" -- Mary Pipher, author of Reviving Ophelia What had happened to my beautiful boy? To our family? What did I do wrong? Those are the wrenching questions that haunted David Sheff\'s journey through his son Nic\'s addiction to drugs and tentative steps toward recovery. Before Nic became addicted to crystal meth, he was a charming boy, joyous and funny, a varsity athlete and honor student adored by his two younger siblings. After meth, he was a trembling wraith who lied, stole, and lived on the streets. David Sheff traces the first warning signs: the denial, the three a.m. phone calls--is it Nic? the police? the hospital? His preoccupation with Nic became an addiction in itself. But as a journalist, he instinctively researched every treatment that might save his son. And he refused to give up on Nic. \"Filled with compelling anecdotes and important insights . . . An eye-opening memoir.\" -- Washington Post', 'beautiful-boy.jpg', '4.79'),
(73, 18, 'Your Four-Year-Old: Wild and Wonderful', 'What is it about four-year-olds that makes them so lovable? What problems do four-year-olds have? What can they do now that they couldn\'t do at three? Drs. Ames and Ilg, recognized authorities on child behavior and development, discuss these and scores of other questions unique to four-year-old girls and boys, and they offer parents practical advice and enlightening psychological insights.', 'your-four-year-old-wild-and-wonderful.jpg', '4.69'),
(74, 18, 'Mayo Clinic Guide to a Healthy Pregnancy', 'Any woman looking for accurate, reliable, and authoritative information on pregnancy will appreciate this book from the world-class Mayo Clinic. The Mayo Clinic Guide to a Healthy Pregnancy offers hundreds of pages of in-depth information that new parents will find useful and informative. Features include week-by-week updates on baby\'s growth, month-by-month changes that mom can expect, and a forty-week pregnancy calendar, as well as a symptom guide and a review of important pregnancy decisions. In this illustrated book you\'ll also find advice on getting pregnant, meal planning, healthy exercise, and safe medication use, along with general tips on becoming a parent. This pregnancy book is the result of the efforts of a collective team of pregnancy experts who find nothing in medicine more exciting and satisfying than the birth of a healthy child with a healthy mother. The Mayo Clinic Guide to a Healthy Pregnancy is an essential pregnancy resource for parents-to-be.', 'mayo-clinic-guide-to-a-healthy-pregnancy.jpg', '4.79'),
(75, 19, 'Anarchy, State, and Utopia', 'In this brilliant and widely acclaimed book, winner of the 1975 National Book Award, Robert Nozick challenges the most commonly held political and social positions of our age--liberal, socialist, and conservative.', 'anarchy-state-and-utopia.jpg', '4.79'),
(76, 19, 'The Truth about Stories : A Native Narrative', 'Winner of the 2003 Trillium Book Award \"Stories are wondrous things,\" award-winning author and scholar Thomas King declares in his 2003 CBC Massey Lectures. \"And they are dangerous.\" Beginning with a traditional Native oral story, King weaves his way through literature and history, religion and politics, popular culture and social protest, gracefully elucidating North America\'s relationship with its Native peoples. Native culture has deep ties to storytelling, and yet no other North American culture has been the subject of more erroneous stories. The Indian of fact, as King says, bears little resemblance to the literary Indian, the dying Indian, the construct so powerfully and often destructively projected by White North America. With keen perception and wit, King illustrates that stories are the key to, and only hope for, human understanding. He compels us to listen well.', 'the-truth-about-stories-a-native-narrative-indigenous-americas.jpg', '4.69'),
(77, 19, 'Parting the Waters : America in the King Years 1954-63', 'In volume one of his America in the King Years, Pulitzer Prize winner Taylor Branch gives a masterly account of the American civil rights movement.Hailed as the most masterful story ever told of the American civil rights movement, Parting the Waters is destined to endure for generations. Moving from the fiery political baptism of Martin Luther King, Jr., to the corridors of Camelot where the Kennedy brothers weighed demands for justice against the deceptions of J. Edgar Hoover, here is a vivid tapestry of America, torn and finally transformed by a revolutionary struggle unequaled since the Civil War. Taylor Branch provides an unsurpassed portrait of King\'s rise to greatness and illuminates the stunning courage and private conflict, the deals, maneuvers, betrayals, and rivalries that determined history behind closed doors, at boycotts and sit-ins, on bloody freedom rides, and through siege and murder. Epic in scope and impact, Branch\'s chronicle definitively captures one of the nation\'s most crucial passages.', 'parting-the-waters-martin-luther-king-and-the-civil-rights-movement-1954-63.jpg', '4.42'),
(78, 19, 'Karl Marx: Selected Writings', 'This second edition of McLellan\'s comprehensive selection of Marx\'s writings includes carefully selected extracts from the whole range of Marx\'s political, philosophical, and economic thought. Each section of the book deals with a different period of Marx\'s life, allowing readers to trace the development of his thought from his early years as a student and political journalist in Germany up through the final letters he wrote in the early 1880s. A fully updated editorial introduction and bibliography has been included for each extract in this new edition.', 'selected-writings.jpg', '4.69'),
(79, 19, 'Eye to Eye', '2017 Expanded Edition. Over one hundred billion-dollar, record-setting catastrophes and/or events occurred while US presidents George H. W. Bush, Bill Clinton, George W. Bush, Barack Obama and Donald Trump were pressuring or calling on Israel to divide their covenant land. The costliest insurance events, the costliest hurricanes, the largest tornado outbreaks, the \" Perfect Storm,\" the 9/11 terror events, and Hurricane Katrina corresponded to White House pressure on Israel to divide their land. The US, the UN, and the EU do not have the authority to divide God s covenant land. Calling the Israeli-Palestinian talks \"Middle East peace talks\" is a false narrative. Jews have a three-thousand-year history with Jerusalem, and Christians have a two-thousand-year history. The biblical heartland of Israel - Judea, Samaria, and East Jerusalem - is not to be part of an Arab State. The Bible declares that Jerusalem will become a burdensome stone, and efforts to divide the city and land will lead to Armageddon, the final battle for Jerusalem. The God of Israel will continue to rebuke those leaders and their nations attempting to divide His land!', 'eye-to-eye-facing-the-consequences-of-dividing-israel.jpg', '4.79'),
(80, 20, 'Letter to a Christian Nation', 'From the new afterword by the author: Humanity has had a long fascination with blood sacrifice. In fact, it has been by no means uncommon for a child to be born into this world only to be patiently and lovingly reared by religious maniacs, who believe that the best way to keep the sun on its course or to ensure a rich harvest is to lead him by tender hand into a field or to a mountaintop and bury, butcher, or burn him alive as offering to an invisible God. The notion that Jesus Christ died for our sins and that his death constitutes a successful propitiation of a \"loving\" God is a direct and undisguised inheritance of the superstitious bloodletting that has plagued bewildered people throughout history. . .', 'letter-to-a-christian-nation.jpg', '4.69'),
(81, 20, 'The Secret Language of Birthdays', 'Combining astrology, numerology, and pure psychic intuition, The Secret Language of Birthdays is a wholly unique compilation that reveals one\'s strengths, weaknesses, and major issues while providing practical advice and spiritual guidance. Many have suspected that your birthday affects your personality and how you relate to others. Nineteen years and over one million copies later, The Secret Language of Birthdays continues to fascinate readers by describing the characteristics associated with being born on a particular day. The 366 personality profiles are based on astrology, numerology, the tarot, and Gary Goldschneider\'s observations of more than 14,000 people. Your strengths, weaknesses, and major concerns will be illuminated while you are given practical advice and spiritual guidance. After you study your profile, it will be hard to resist examining those of family, friends, colleagues, and even celebrities.', 'the-secret-language-of-birthdays-personology-profiles-for-each-day-of-the-year.jpg', '18.59'),
(82, 20, 'I Don\'t Have Enough Faith to Be an Atheist', 'To some, the concept of having faith in a higher power or a set of religious beliefs is nonsensical. Indeed, many view religion in general, and Christianity in particular, as unfounded and unreasonable. Norman Geisler and Frank Turek argue, however, that Christianity is not only more reasonable than all other belief systems, but is indeed more rational than unbelief itself. With conviction and clear thinking, Geisler and Turek guide readers through some of the traditional, tested arguments for the existence of a creator God. They move into an examination of the source of morality and the reliability of the New Testament accounts concerning Jesus. The final section of the book deals with a detailed investigation of the claims of Christ. This volume will be an interesting read for those skeptical about Christianity, as well as a helpful resource for Christians seeking to articulate a more sophisticated defense of their faith.', 'i-dont-have-enough-faith-to-be-an-atheist.jpg', '19.00'),
(83, 20, 'Knowing God', 'One of the top 50 books that have shaped evangelicals (Christianity Today, 2006)Platinum Book Award, Evangelical Christian Publishing AssociationFor over 40 years, J. I. Packer\'s classic has been an important tool to help Christians around the world discover the wonder, the glory and the joy of knowing God. In 2006, Christianity Today voted this title one of the top 50 books that have shaped evangelicals. This edition is updated with Americanized language and spelling and a new preface by the author.Stemming from Packer\'s profound theological knowledge, Knowing God brings together two important facets of the Christian faith-- knowing about God and also knowing God through the context of a close relationship with the person of Jesus Christ. Written in an engaging and practical tone, this thought-provoking work seeks to transform and enrich the Christian understanding of God. Explaining both who God is and how we can relate to him, Packer divides his book into three sections: The first directs our attention to how and why we know God, the second to the attributes of God and the third to the benefits enjoyed by a those who know him intimately. This guide leads readers into a greater understanding of God while providing advice to gaining a closer relationship with him as a result.', 'knowing-god.jpg', '4.79'),
(84, 21, 'Everyone Poops', 'Since we all eat, we all must poop. All of us! Everyone!This wonderful, modern-day toddler classic presents information that children both want and need in a refreshingly honest, informative, and age-appropriate way.', 'everyone-poops-my-body-science-series.jpg', '4.69'),
(85, 21, 'Never Cry Wolf', 'Hordes of bloodthirsty wolves are slaughtering the arctic caribou, and the government\'s Wildlife Service assigns naturalist Farely Mowat to investigate. Mowat is dropped alone onto the frozen tundra, where he begins his mission to live among the howling wolf packs and study their waves. Contact with his quarry comes quickly, and Mowat discovers not a den of marauding killers but a courageous family of skillful providers and devoted protectors of their young. As Mowat comes closer to the wolf world, he comes to fear with them on onslaught of bounty hunters and government exterminators out to erase the noble wolf community from the Arctic. Never Cry Wolf is one of the brilliant narratives on the myth and magical world of wild wolves and man\'s true place among the creatures of nature. \"We have doomed the wolf not for what it is, but for what we deliberately and mistakenly perceive it to be -- the mythological epitome of a savage, ruthless killer -- which is, in reality, no more than the reflected image of ourself.\" -- from the new preface to Never Cry Wolf. From the Paperback edition.', 'never-cry-wolf--the-amazing-true-story-of-life-among-arctic-wolves.jpg', '4.99'),
(86, 21, 'A Short History of Nearly Everything', 'No Synopsis Available.', 'a-short-history-of-nearly-everything.jpg', '4.89'),
(87, 21, 'Incognito : The Secret Lives of the Brain', 'If the conscious mind--the part you consider to be you--is just the tip of the iceberg, what is the rest doing? In this sparkling and provocative book, renowned neuroscientist David Eagleman navigates the depths of the subconscious brain to illuminate its surprising mysteries. Why can your foot move halfway to the brake pedal before you become consciously aware of danger ahead? Is there a true Mel Gibson? How is your brain like a conflicted democracy engaged in civil war? What do Odysseus and the subprime mortgage meltdown have in common? Why are people whose names begin with J more like to marry other people whose names begin with J? And why is it so difficult to keep a secret? Taking in brain damage, plane spotting, dating, drugs, beauty, infidelity, synesthesia, criminal law, artificial intelligence, and visual illusions, Incognito is a thrilling subsurface exploration of the mind and all its contradictions.', 'incognito-the-secret-lives-of-the-brain.jpg', '4.69'),
(88, 22, 'Toxic Parents', 'Are you the child of toxic parents? When you were a child... - Did your parents tell you you were bad or worthless? - Did your parents use physical pain to discipline you? - Did you have to take care of your parents because of their problems? - Were you often frightened of your parents? - Did your parents do anything to you that had to be kept secret? Now that you\'re an adult... - Do your parents still treat you as if you were a child? - Do you have intense emotional or physical reactions after spending time with your parents? - Do your parents control you with threats or guilt? Do they manipulate you with money? - Do you feel that no matter what you do, it\'s never good enough for your parents? In this remarkable self-help guide, Dr. Susan Forward draws on case histories and the real-life voices of adult children of toxic parents to help you free yourself from the frustrating patterns of your relationship with your parents -- and discover a new world of self-confidence, inner strength, and emotional independence.', 'toxic-parents.jpg', '4.79'),
(89, 22, 'Living Sober', 'Living Sober is an extremely informative book which does not offer a plan for getting sober but does offer us sound advice about how to stay sober.Living Sober is an extremely informative book which does not offer a plan for getting sober but does offer us sound advice about how to stay sober. Basic, essential information from Alcoholics Anonymous. As the book states, \"Anyone can get sober. . .the trick is to live sober.\"', 'living-sober.jpg', '4.49'),
(90, 22, 'The Dance of Anger', 'Addresses the problem women have in hiding or denying their anger. Explains the repeating patterns in relationships where the women is suppressing her negative emotions. Includes how to use that anger to create change.', 'the-dance-of-anger.jpg', '4.79'),
(91, 22, 'Monkey Mind : A Memoir of Anxiety', 'A wildly acclaimed New York Times bestseller, this uplifting, smart, and funny memoir provides hope and understanding to the 40 million Americans who suffer from anxiety disorders. Daniel Smith\'s Monkey Mind is the stunning articulation of what it is like to live with anxiety. As he travels through anxiety\'s demonic layers, Smith defangs the disorder with great humor and evocatively expresses its self-destructive absurdities and painful internal coherence. Aaron Beck, the most influential doctor in modern psychotherapy, says that \"Monkey Mind does for anxiety what William Styron\'s Darkness Visible did for depression.\" Neurologist and bestselling writer Oliver Sacks says, \"I read Monkey Mind with admiration for its bravery and clarity. . . . I broke out into explosive laughter again and again.\" Here, finally, comes relief and recognition to all those who want someone to put what they feel, or what their loved ones feel, into words.', 'monkey-mind-a-memoir-of-anxiety.jpg', '4.69'),
(92, 22, 'Walter the Farting Dog', 'Warning: This book may cause flatulence . Walter is a fine dog, except for one small problem: he has gas. He can\'t help it; it\'s just the way he is. Fortunately, the kids Billy and Betty love him regardless, but Father says he\'s got to go Poor Walter, he\'s going to the dog pound tomorrow. And then, in the night, burglars strike. Walter has his chance to be a hero. A children\'s beloved classic, this story will have kids rolling on the floor with laughter. Adults are permitted to laugh too.', 'walter-the-farting-dog.jpg', '4.69'),
(93, 23, 'Deep Survival : Who Lives, Who Dies, and Why', 'In ?Deep Survival?, Laurence Gonzalez combines hard science and powerful storytelling to illustrate the mysteries of survival, whether in the wilderness or in meeting any of life\'s great challenges. This gripping narrative, the first book to describe the art and science of survival, will change the way you see the world. Everyone has a mountain to climb. Everyone has a wilderness inside.', 'deep-survival-who-lives-who-dies-and-why.jpg', '4.69'),
(94, 23, 'Total Immersion : A Revolutionary Way to Swim Better and Faster', 'A self-teaching programme for all levels. Step-by-step skill drills are provided which include how to: improve strokes to speed up conditioning; eliminate drag and create more propulsion with less energy; burn off fat through swimming; and use dry-land exercises to improve results in the water.', 'total-immersion-a-revolutionary-way-to-swim-better-and-faster.jpg', '4.79'),
(95, 24, 'Killer (Pretty Little Liars, Book 6)', '#1 New York Times bestselling seriesThe sixth book in the #1 New York Times bestselling series that inspired the hit ABC Family TV show Pretty Little Liars.Hanna, Aria, Spencer, and Emily have been lying ever since they became friends with beautiful Alison DiLaurentis. And their bad-girl ways didn\'t die with her. Hanna\'s on a mission to corrupt Rosewood\'s youth, starting with a very attractive sophomore. Aria\'s snooping into her boyfriend\'s past. Spencer\'s stealingâ€”from her family. And pure little Emily\'s abstaining from abstinence. The girls should be careful, though. There\'s a new A in town turning up the heat. And this time Rosewood is going to burn.Full of unexpected twists and shocking revelations, Killer is the sixth book in New York Times bestselling author Sara Shepardâ€™s compelling Pretty Little Liars series.', 'killer.jpg', '4.79'),
(96, 24, 'City of Bones', 'No Synopsis Available.', 'city-of-bones.jpg', '4.79'),
(97, 24, 'The Book Thief', 'DON\'T MISS BRIDGE OF CLAY , MARKUS ZUSAK\'S FIRST NOVEL SINCE THE BOOK THIEF . The extraordinary #1 New York Times bestseller that is now a major motion picture, Markus Zusak\'s unforgettable story is about the ability of books to feed the soul. Nominated as one of America\'s best-loved novels by PBS\'s The Great American Read . When Death has a story to tell, you listen. It is 1939. Nazi Germany. The country is holding its breath. Death has never been busier, and will become busier still. Liesel Meminger is a foster girl living outside of Munich, who scratches out a meager existence for herself by stealing when she encounters something she can\'t resist-books. With the help of her accordion-playing foster father, she learns to read and shares her stolen books with her neighbors during bombing raids as well as with the Jewish man hidden in her basement. In superbly crafted writing that burns with intensity, award-winning author Markus Zusak, author of I Am the Messenger, has given us one of the most enduring stories of our time. \"The kind of book that can be life-changing.\" -- The New York Times \"Deserves a place on the same shelf with The Diary of a Young Girl by Anne Frank.\" -- USA Today', 'the-book-thief.jpg', '4.69'),
(98, 25, 'Out of Africa: and Shadows on the Grass', 'With classic simplicity and a painter\'s feeling for atmosphere and detail, Isak Dinesen tells of the years she spent from 1914 to 1931 managing a coffee plantation in Kenya.  Edition Details', 'out-of-africa-and-shadows-on-the-grass.jpg', '4.69'),
(99, 25, 'When Heaven and Earth Changed Places', 'It is said that in war heaven and earth change places not once, but many times. When Heaven and Earth Changed Places is the haunting memoir of a girl on the verge of womanhood in a world turned upside down. The youngest of six children in a close-knit Buddhist family, Le Ly Hayslip was twelve years old when U.S. helicopters langed in Ky La, her tiny village in central Vietnam. As the government and Viet Cong troops fought in and around Ky La, both sides recruited children as spies and saboteurs. Le Ly was one of those children. Before the age of sixteen, Le Ly had suffered near-starvation, imprisonment, torture, rape, and the deaths of beloved family members--but miraculously held fast to her faith in humanity. And almost twenty years after her escape to Ameica, she was drawn inexorably back to the devastated country and family she left behind. Scenes of this joyous reunion are interwoven with the brutal war years, offering a poignant picture of vietnam, then and now, and of a courageous woman who experienced the true horror of the Vietnam War--and survived to tell her unforgettable story.', 'when-heaven-and-earth-changed-places.jpg', '4.79'),
(100, 25, 'The curve of time', 'No Synopsis Available.', 'the-curve-of-time.jpg', '5.59'),
(101, 25, 'A Small Place', 'A brilliant look at colonialism and its effects in Antigua--by the author of Annie John\"If you go to Antigua as a tourist, this is what you will see. If you come by aeroplane, you will land at the V. C. Bird International Airport. Vere Cornwall (V. C.) Bird is the Prime Minister of Antigua. You may be the sort of tourist who would wonder why a Prime Minister would want an airport named after him--why not a school, why not a hospital, why not some great public monument. You are a tourist and you have not yet seen . . .\"So begins Jamaica Kincaid\'s expansive essay, which shows us what we have not yet seen of the ten-by-twelve-mile island in the British West Indies where she grew up.Lyrical, sardonic, and forthright by turns, in a Swiftian mode, A Small Place cannot help but amplify our vision of one small place and all that it signifies.', 'a-small-place.jpg', '4.79');

-- --------------------------------------------------------

--
-- Table structure for table `users`
--

DROP TABLE IF EXISTS `users`;
CREATE TABLE IF NOT EXISTS `users` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `first_name` varchar(100) NOT NULL,
  `last_name` varchar(100) NOT NULL,
  `email` varchar(100) NOT NULL,
  `username` varchar(100) NOT NULL,
  `password` varchar(100) NOT NULL,
  `join_date` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=latin1;

--
-- Dumping data for table `users`
--

INSERT INTO `users` (`id`, `first_name`, `last_name`, `email`, `username`, `password`, `join_date`) VALUES
(1, 'Khoa', 'Mai', 'chronicle1951@gmail.com', 'khoa', '123', '2019-05-18 12:52:37');

--
-- Constraints for dumped tables
--

--
-- Constraints for table `products`
--
ALTER TABLE `products`
  ADD CONSTRAINT `products_ibfk_1` FOREIGN KEY (`category_id`) REFERENCES `categories` (`id`);
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
